"""Closed vocabularies shared by Research Retrieval Calibrator contracts."""

from enum import StrEnum


class ProjectStage(StrEnum):
    INIT = "INIT"
    CLARIFYING = "CLARIFYING"
    ROUND1_SEARCHING = "ROUND1_SEARCHING"
    WAITING_FOR_FEEDBACK = "WAITING_FOR_FEEDBACK"
    ROUND2_SEARCHING = "ROUND2_SEARCHING"
    WAITING_FOR_DIRECTION_CONFIRMATION = "WAITING_FOR_DIRECTION_CONFIRMATION"
    FINALIZED = "FINALIZED"


class QueryBranch(StrEnum):
    DIRECT_INTERSECTION = "DIRECT_INTERSECTION"
    PROBLEM_DOMAIN = "PROBLEM_DOMAIN"
    METHOD_DOMAIN = "METHOD_DOMAIN"
    BRIDGE_DOMAIN = "BRIDGE_DOMAIN"


class QueryBreadth(StrEnum):
    NARROW = "NARROW"
    MEDIUM = "MEDIUM"
    WIDE = "WIDE"


class Relevance(StrEnum):
    HIGH = "HIGH"
    PARTIAL = "PARTIAL"
    IRRELEVANT = "IRRELEVANT"


class FeedbackAspect(StrEnum):
    OBJECT = "OBJECT"
    TASK = "TASK"
    METHOD = "METHOD"
    PHYSICS = "PHYSICS"
    BRIDGE = "BRIDGE"
    EVALUATION = "EVALUATION"


class EvidenceSlot(StrEnum):
    PROBLEM_EXISTENCE = "PROBLEM_EXISTENCE"
    CURRENT_METHODS = "CURRENT_METHODS"
    METHOD_TRANSFERABILITY = "METHOD_TRANSFERABILITY"
    IMPLEMENTATION_PATH = "IMPLEMENTATION_PATH"
    EVALUATION_BASIS = "EVALUATION_BASIS"


class SupportLevel(StrEnum):
    DIRECT = "DIRECT"
    INDIRECT = "INDIRECT"
    HYPOTHETICAL = "HYPOTHETICAL"


class MethodConstraint(StrEnum):
    REQUIRED = "REQUIRED"
    PREFERRED = "PREFERRED"
    OPEN = "OPEN"
